### ISSUE TITLE
how do I get file-manager to show on the tab bar

### ISSUE THREAD

**Issue by mark-hahn** [Salandora/OctoPrint-FileManager#22]
I have put this in my ~/.octoprint/config.yaml ...
```
appearance:
  color: green
  components:
    order:
      tab:
      - temperature
      - control
      - gcodeviewer
      - terminal
      - file_manager
      - plugin_enclosure
  name: CR-10
```

... but the plugin_enclosure is showing before the file manager so it is pushed off to the drop-down which is a pita.

What am I doing wrong?

Is there some way to have all tabs shown via on of the many standard ways to do that?
